// <auto-generated />
using System;
using GUIWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GUIWebApi.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260210123910_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GUIWebApi.Models.Category1", b =>
                {
                    b.Property<int>("Category1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category1Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Category1Id");

                    b.ToTable("Categories1");
                });

            modelBuilder.Entity("GUIWebApi.Models.InventoryFile", b =>
                {
                    b.Property<int>("InventoryFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryFileId"));

                    b.Property<string>("ContentHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("PhysicalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventoryFileId");

                    b.ToTable("InventoryFiles");
                });

            modelBuilder.Entity("GUIWebApi.Models.Product1", b =>
                {
                    b.Property<int>("Product1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product1Id"));

                    b.Property<int>("Category1Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserFileId")
                        .HasColumnType("int");

                    b.HasKey("Product1Id");

                    b.HasIndex("Category1Id");

                    b.HasIndex("UserFileId");

                    b.ToTable("Products1");
                });

            modelBuilder.Entity("GUIWebApi.Models.UserFile", b =>
                {
                    b.Property<int>("UserFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserFileId"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryFileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserFileId");

                    b.HasIndex("InventoryFileId");

                    b.ToTable("UserFiles");
                });

            modelBuilder.Entity("GUIWebApi.Models.Product1", b =>
                {
                    b.HasOne("GUIWebApi.Models.Category1", "Category1")
                        .WithMany("Products1")
                        .HasForeignKey("Category1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GUIWebApi.Models.UserFile", "UserFile")
                        .WithMany("Products1")
                        .HasForeignKey("UserFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category1");

                    b.Navigation("UserFile");
                });

            modelBuilder.Entity("GUIWebApi.Models.UserFile", b =>
                {
                    b.HasOne("GUIWebApi.Models.InventoryFile", "InventoryFile")
                        .WithMany("UserFiles")
                        .HasForeignKey("InventoryFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryFile");
                });

            modelBuilder.Entity("GUIWebApi.Models.Category1", b =>
                {
                    b.Navigation("Products1");
                });

            modelBuilder.Entity("GUIWebApi.Models.InventoryFile", b =>
                {
                    b.Navigation("UserFiles");
                });

            modelBuilder.Entity("GUIWebApi.Models.UserFile", b =>
                {
                    b.Navigation("Products1");
                });
#pragma warning restore 612, 618
        }
    }
}
